Ext.define('Mfw.Globals', {
    alternateClassName: 'Globals',
    singleton: true,

    protocols: [
        { text: 'HOPOPT', value: 0 },
        { text: 'ICMP', value: 1 },
        { text: 'IGMP', value: 2 },
        { text: 'GGP', value: 3 },
        { text: 'IP-in-IP', value: 4 },
        { text: 'ST', value: 5 },
        { text: 'TCP', value: 6 },
        { text: 'CBT', value: 7 },
        { text: 'EGP', value: 8 },
        { text: 'IGP', value: 9 },
        { text: 'BBN-RCC-MON', value: 10 },
        { text: 'NVP-II', value: 11 },
        { text: 'PUP', value: 12 },
        { text: 'ARGUS', value: 13 },
        { text: 'EMCON', value: 14 },
        { text: 'XNET', value: 15 },
        { text: 'CHAOS', value: 16 },
        { text: 'UDP', value: 17 },
        { text: 'MUX', value: 18 },
        { text: 'DCN-MEAS', value: 19 },
        { text: 'HMP', value: 20 },
        { text: 'PRM', value: 21 },
        { text: 'XNS-IDP', value: 22 },
        { text: 'TRUNK-1', value: 23 },
        { text: 'TRUNK-2', value: 24 },
        { text: 'LEAF-1', value: 25 },
        { text: 'LEAF-2', value: 26 },
        { text: 'RDP', value: 27 },
        { text: 'IRTP', value: 28 },
        { text: 'ISO-TP4', value: 29 },
        { text: 'NETBLT', value: 30 },
        { text: 'MFE-NSP', value: 31 },
        { text: 'MERIT-INP', value: 32 },
        { text: 'DCCP', value: 33 },
        { text: '3PC', value: 34 },
        { text: 'IDPR', value: 35 },
        { text: 'XTP', value: 36 },
        { text: 'DDP', value: 37 },
        { text: 'IDPR-CMTP', value: 38 },
        { text: 'TP++', value: 39 },
        { text: 'IL', value: 40 },
        { text: 'IPv6', value: 41 },
        { text: 'SDRP', value: 42 },
        { text: 'IPv6-Route', value: 43 },
        { text: 'IPv6-Frag', value: 44 },
        { text: 'IDRP', value: 45 },
        { text: 'RSVP', value: 46 },
        { text: 'GRE', value: 47 },
        { text: 'MHRP', value: 48 },
        { text: 'BNA', value: 49 },
        { text: 'ESP', value: 50 },
        { text: 'AH', value: 51 },
        { text: 'I-NLSP', value: 52 },
        { text: 'SWIPE', value: 53 },
        { text: 'NARP', value: 54 },
        { text: 'MOBILE', value: 55 },
        { text: 'TLSP', value: 56 },
        { text: 'SKIP', value: 57 },
        { text: 'IPv6-ICMP', value: 58 },
        { text: 'IPv6-NoNxt', value: 59 },
        { text: 'IPv6-Opts', value: 60 },
        { text: 'CFTP', value: 62 },
        { text: 'SAT-EXPAK', value: 64 },
        { text: 'KRYPTOLAN', value: 65 },
        { text: 'RVD', value: 66 },
        { text: 'IPPC', value: 67 },
        { text: 'SAT-MON', value: 69 },
        { text: 'VISA', value: 70 },
        { text: 'IPCU', value: 71 },
        { text: 'CPNX', value: 72 },
        { text: 'CPHB', value: 73 },
        { text: 'WSN', value: 74 },
        { text: 'PVP', value: 75 },
        { text: 'BR-SAT-MON', value: 76 },
        { text: 'SUN-ND', value: 77 },
        { text: 'WB-MON', value: 78 },
        { text: 'WB-EXPAK', value: 79 },
        { text: 'ISO-IP', value: 80 },
        { text: 'VMTP', value: 81 },
        { text: 'SECURE-VMTP', value: 82 },
        { text: 'VINES', value: 83 },
        { text: 'TTP', value: 84 },
        { text: 'NSFNET-IGP', value: 85 },
        { text: 'DGP', value: 86 },
        { text: 'TCF', value: 87 },
        { text: 'EIGRP', value: 88 },
        { text: 'OSPF', value: 89 },
        { text: 'Sprite-RPC', value: 90 },
        { text: 'LARP', value: 91 },
        { text: 'MTP', value: 92 },
        { text: 'AX.25', value: 93 },
        { text: 'IPIP', value: 94 },
        { text: 'MICP', value: 95 },
        { text: 'SCC-SP', value: 96 },
        { text: 'ETHERIP', value: 97 },
        { text: 'ENCAP', value: 98 },
        { text: 'GMTP', value: 100 },
        { text: 'IFMP', value: 101 },
        { text: 'PNNI', value: 102 },
        { text: 'PIM', value: 103 },
        { text: 'ARIS', value: 104 },
        { text: 'SCPS', value: 105 },
        { text: 'QNX', value: 106 },
        { text: 'A/N', value: 107 },
        { text: 'IPComp', value: 108 },
        { text: 'SNP', value: 109 },
        { text: 'Compaq-Peer', value: 110 },
        { text: 'IPX-in-IP', value: 111 },
        { text: 'VRRP', value: 112 },
        { text: 'PGM', value: 113 },
        { text: 'L2TP', value: 115 },
        { text: 'DDX', value: 116 },
        { text: 'IATP', value: 117 },
        { text: 'STP', value: 118 },
        { text: 'SRP', value: 119 },
        { text: 'UTI', value: 120 },
        { text: 'SMP', value: 121 },
        { text: 'SM', value: 122 },
        { text: 'PTP', value: 123 },
        { text: 'IS-IS', value: 124 },
        { text: 'FIRE', value: 125 },
        { text: 'CRTP', value: 126 },
        { text: 'CRUDP', value: 127 },
        { text: 'SSCOPMCE', value: 128 },
        { text: 'IPLT', value: 129 },
        { text: 'SPS', value: 130 },
        { text: 'PIPE', value: 131 },
        { text: 'SCTP', value: 132 },
        { text: 'FC', value: 133 },
        { text: 'RSVP-E2E-IGNORE', value: 134 },
        { text: 'Mobility', value: 135 },
        { text: 'UDPLite', value: 136 },
        { text: 'MPLS-in-IP', value: 137 },
        { text: 'manet', value: 138 },
        { text: 'HIP', value: 139 },
        { text: 'Shim6', value: 140 },
        { text: 'WESP', value: 141 },
        { text: 'ROHC', value: 142 }
    ],

    prefixes: [
        { value: '', text: 'Not set' },
        { value: 32, text: '/32 - 255.255.255.255' },
        { value: 31, text: '/31 - 255.255.255.254' },
        { value: 30, text: '/30 - 255.255.255.252' },
        { value: 29, text: '/29 - 255.255.255.248' },
        { value: 28, text: '/28 - 255.255.255.240' },
        { value: 27, text: '/27 - 255.255.255.224' },
        { value: 26, text: '/26 - 255.255.255.192' },
        { value: 25, text: '/25 - 255.255.255.128' },
        { value: 24, text: '/24 - 255.255.255.0' },
        { value: 23, text: '/23 - 255.255.254.0' },
        { value: 22, text: '/22 - 255.255.252.0' },
        { value: 21, text: '/21 - 255.255.248.0' },
        { value: 20, text: '/20 - 255.255.240.0' },
        { value: 19, text: '/19 - 255.255.224.0' },
        { value: 18, text: '/18 - 255.255.192.0' },
        { value: 17, text: '/17 - 255.255.128.0' },
        { value: 16, text: '/16 - 255.255.0.0' },
        { value: 15, text: '/15 - 255.254.0.0' },
        { value: 14, text: '/14 - 255.252.0.0' },
        { value: 13, text: '/13 - 255.248.0.0' },
        { value: 12, text: '/12 - 255.240.0.0' },
        { value: 11, text: '/11 - 255.224.0.0' },
        { value: 10, text: '/10 - 255.192.0.0' },
        { value: 9, text: '/9 - 255.128.0.0' },
        { value: 8, text: '/8 - 255.0.0.0' },
        { value: 7, text: '/7 - 254.0.0.0' },
        { value: 6, text: '/6 - 252.0.0.0' },
        { value: 5, text: '/5 - 248.0.0.0' },
        { value: 4, text: '/4 - 240.0.0.0' },
        { value: 3, text: '/3 - 224.0.0.0' },
        { value: 2, text: '/2 - 192.0.0.0' },
        { value: 1, text: '/1 - 128.0.0.0' },
        { value: 0, text: '/0 - 0.0.0.0' }
    ],

    operators: [
        { text: 'Equals'.t(),           value: 'EQ',       symbol: '='        },
        { text: 'Not Equals'.t(),       value: 'NE',       symbol: '!='       },
        { text: 'Greater Than'.t(),     value: 'GT',       symbol: '>'        },
        { text: 'Less Than'.t(),        value: 'LT',       symbol: '<'        },
        { text: 'Greater or Equal'.t(), value: 'GE',       symbol: '>='       },
        { text: 'Less or Equal'.t(),    value: 'LE',       symbol: '<='       },
        { text: 'Like'.t(),           value: 'LIKE',     symbol: 'like'     },
        { text: 'Not Like'.t(),   value: 'NOT_LIKE', symbol: 'not like' },
        { text: 'Is'.t(),               value: 'IS',       symbol: 'is'       },
        { text: 'Is Not'.t(),       value: 'IS_NOT',   symbol: 'is not'   },
        { text: 'In'.t(),               value: 'IN',       symbol: 'in'       },
        { text: 'Not In'.t(),       value: 'NOT_IN',   symbol: 'not in'   }
    ],

    countries: [
        { value: 'AF', text: 'AFGHANISTAN' },
        { value: 'AL', text: 'ALBANIA' },
        { value: 'DZ', text: 'ALGERIA' },
        { value: 'AS', text: 'AMERICAN SAMOA' },
        { value: 'AD', text: 'ANDORRA' },
        { value: 'AO', text: 'ANGOLA' },
        { value: 'AI', text: 'ANGUILLA' },
        { value: 'AQ', text: 'ANTARCTICA' },
        { value: 'AG', text: 'ANTIGUA AND BARBUDA' },
        { value: 'AR', text: 'ARGENTINA' },
        { value: 'AM', text: 'ARMENIA' },
        { value: 'AW', text: 'ARUBA' },
        { value: 'AU', text: 'AUSTRALIA' },
        { value: 'AT', text: 'AUSTRIA' },
        { value: 'AZ', text: 'AZERBAIJAN' },
        { value: 'BS', text: 'BAHAMAS' },
        { value: 'BH', text: 'BAHRAIN' },
        { value: 'BD', text: 'BANGLADESH' },
        { value: 'BB', text: 'BARBADOS' },
        { value: 'BY', text: 'BELARUS' },
        { value: 'BE', text: 'BELGIUM' },
        { value: 'BZ', text: 'BELIZE' },
        { value: 'BJ', text: 'BENIN' },
        { value: 'BM', text: 'BERMUDA' },
        { value: 'BT', text: 'BHUTAN' },
        { value: 'BO', text: 'OLIVIA' },
        { value: 'BA', text: 'BOSNIA AND HERZEGOVINA' },
        { value: 'BW', text: 'BOTSWANA' },
        { value: 'BV', text: 'BOUVET ISLAND' },
        { value: 'BR', text: 'BRAZIL' },
        { value: 'IO', text: 'BRITISH INDIAN OCEAN TERRITORY' },
        { value: 'BN', text: 'BRUNEI DARUSSALAM' },
        { value: 'BG', text: 'BULGARIA' },
        { value: 'BF', text: 'BURKINA FASO' },
        { value: 'BI', text: 'BURUNDI' },
        { value: 'KH', text: 'CAMBODIA' },
        { value: 'CM', text: 'CAMEROON' },
        { value: 'CA', text: 'CANADA' },
        { value: 'CV', text: 'CAPE VERDE' },
        { value: 'KY', text: 'CAYMAN ISLANDS' },
        { value: 'CF', text: 'CENTRAL AFRICAN REPUBLIC' },
        { value: 'TD', text: 'CHAD' },
        { value: 'CL', text: 'CHILE' },
        { value: 'CN', text: 'HINA' },
        { value: 'CX', text: 'HRISTMAS ISLAND' },
        { value: 'CC', text: 'COCOS (KEELING) ISLANDS' },
        { value: 'CO', text: 'COLOMBIA' },
        { value: 'KM', text: 'COMOROS' },
        { value: 'CG', text: 'CONGO' },
        { value: 'CD', text: 'CONGO, THE DEMOCRATIC REPUBLIC OF' },
        { value: 'CK', text: 'COOK ISLANDS' },
        { value: 'CR', text: 'COSTA RICA' },
        { value: 'CI', text: 'CÔTE D\'IVOIRE' },
        { value: 'HR', text: 'CROATIA' },
        { value: 'CU', text: 'CUBA' },
        { value: 'CY', text: 'CYPRUS' },
        { value: 'CZ', text: 'CZECH REPUBLIC' },
        { value: 'DK', text: 'DENMARK' },
        { value: 'DJ', text: 'DJIBOUTI' },
        { value: 'DM', text: 'DOMINICA' },
        { value: 'DO', text: 'DOMINICAN REPUBLIC' },
        { value: 'EC', text: 'ECUADOR' },
        { value: 'EG', text: 'EGYPT' },
        { value: 'SV', text: 'EL SALVADOR' },
        { value: 'GQ', text: 'EQUATORIAL GUINEA' },
        { value: 'ER', text: 'ERITREA' },
        { value: 'EE', text: 'ESTONIA' },
        { value: 'ET', text: 'ETHIOPIA' },
        { value: 'FK', text: 'FALKLAND ISLANDS (MALVINAS)' },
        { value: 'FO', text: 'AROE ISLANDS' },
        { value: 'FJ', text: 'FIJI' },
        { value: 'FI', text: 'FINLAND' },
        { value: 'FR', text: 'FRANCE' },
        { value: 'GF', text: 'FRENCH GUIANA' },
        { value: 'PF', text: 'FRENCH POLYNESIA' },
        { value: 'TF', text: 'FRENCH SOUTHERN TERRITORIES' },
        { value: 'GA', text: 'GABON' },
        { value: 'GM', text: 'GAMBIA' },
        { value: 'GE', text: 'GEORGIA' },
        { value: 'DE', text: 'GERMANY' },
        { value: 'GH', text: 'GHANA' },
        { value: 'GI', text: 'GIBRALTAR' },
        { value: 'GR', text: 'GREECE' },
        { value: 'GL', text: 'GREENLAND' },
        { value: 'GD', text: 'GRENADA' },
        { value: 'GP', text: 'GUADELOUPE' },
        { value: 'GU', text: 'GUAM' },
        { value: 'GT', text: 'GUATEMALA' },
        { value: 'GN', text: 'GUINEA' },
        { value: 'GW', text: 'GUINEA-BISSAU' },
        { value: 'GY', text: 'GUYANA' },
        { value: 'HT', text: 'HAITI' },
        { value: 'HM', text: 'HEARD ISLAND AND MCDONALD ISLANDS' },
        { value: 'HN', text: 'HONDURAS' },
        { value: 'HK', text: 'HONG KONG' },
        { value: 'HU', text: 'HUNGARY' },
        { value: 'IS', text: 'ICELAND' },
        { value: 'IN', text: 'INDIA' },
        { value: 'ID', text: 'INDONESIA' },
        { value: 'IR', text: 'IRAN, ISLAMIC REPUBLIC OF' },
        { value: 'IQ', text: 'IRAQ' },
        { value: 'IE', text: 'IRELAND' },
        { value: 'IL', text: 'ISRAEL' },
        { value: 'IT', text: 'ITALY' },
        { value: 'JM', text: 'JAMAICA' },
        { value: 'JP', text: 'JAPAN' },
        { value: 'JO', text: 'JORDAN' },
        { value: 'KZ', text: 'KAZAKHSTAN' },
        { value: 'KE', text: 'KENYA' },
        { value: 'KI', text: 'KIRIBATI' },
        { value: 'KP', text: 'KOREA, DEMOCRATIC PEOPLE\'S REPUBLIC OF' },
        { value: 'KR', text: 'KOREA, REPUBLIC OF' },
        { value: 'KW', text: 'KUWAIT' },
        { value: 'KG', text: 'KYRGYZSTAN' },
        { value: 'LA', text: 'LAO PEOPLE\'S DEMOCRATIC REPUBLIC' },
        { value: 'LV', text: 'LATVIA' },
        { value: 'LB', text: 'LEBANON' },
        { value: 'LS', text: 'LESOTHO' },
        { value: 'LR', text: 'LIBERIA' },
        { value: 'LY', text: 'LIBYAN ARAB JAMAHIRIYA' },
        { value: 'LI', text: 'LIECHTENSTEIN' },
        { value: 'LT', text: 'LITHUANIA' },
        { value: 'LU', text: 'LUXEMBOURG' },
        { value: 'MO', text: 'MACAO' },
        { value: 'MK', text: 'MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF' },
        { value: 'MG', text: 'MADAGASCAR' },
        { value: 'MW', text: 'MALAWI' },
        { value: 'MY', text: 'MALAYSIA' },
        { value: 'MV', text: 'MALDIVES' },
        { value: 'ML', text: 'MALI' },
        { value: 'MT', text: 'MALTA' },
        { value: 'MH', text: 'MARSHALL ISLANDS' },
        { value: 'MQ', text: 'MARTINIQUE' },
        { value: 'MR', text: 'MAURITANIA' },
        { value: 'MU', text: 'MAURITIUS' },
        { value: 'YT', text: 'MAYOTTE' },
        { value: 'MX', text: 'MEXICO' },
        { value: 'FM', text: 'MICRONESIA, FEDERATED STATES OF' },
        { value: 'MD', text: 'MOLDOVA, REPUBLIC OF' },
        { value: 'MC', text: 'MONACO' },
        { value: 'MN', text: 'MONGOLIA' },
        { value: 'MS', text: 'MONTSERRAT' },
        { value: 'MA', text: 'MOROCCO' },
        { value: 'MZ', text: 'MOZAMBIQUE' },
        { value: 'MM', text: 'MYANMAR' },
        { value: 'NA', text: 'NAMIBIA' },
        { value: 'NR', text: 'NAURU' },
        { value: 'NP', text: 'NEPAL' },
        { value: 'NL', text: 'NETHERLANDS' },
        { value: 'AN', text: 'NETHERLANDS ANTILLES' },
        { value: 'NC', text: 'NEW CALEDONIA' },
        { value: 'NZ', text: 'NEW ZEALAND' },
        { value: 'NI', text: 'NICARAGUA' },
        { value: 'NE', text: 'NIGER' },
        { value: 'NG', text: 'NIGERIA' },
        { value: 'NU', text: 'NIUE' },
        { value: 'NF', text: 'NORFOLK ISLAND' },
        { value: 'MP', text: 'NORTHERN MARIANA ISLANDS' },
        { value: 'NO', text: 'NORWAY' },
        { value: 'OM', text: 'OMAN' },
        { value: 'PK', text: 'PAKISTAN' },
        { value: 'PW', text: 'PALAU' },
        { value: 'PS', text: 'PALESTINIAN TERRITORY, OCCUPIED' },
        { value: 'PA', text: 'PANAMA' },
        { value: 'PG', text: 'PAPUA NEW GUINEA' },
        { value: 'PY', text: 'PARAGUAY' },
        { value: 'PE', text: 'PERU' },
        { value: 'PH', text: 'PHILIPPINES' },
        { value: 'PN', text: 'PITCAIRN' },
        { value: 'PL', text: 'POLAND' },
        { value: 'PT', text: 'PORTUGAL' },
        { value: 'PR', text: 'PUERTO RICO' },
        { value: 'QA', text: 'QATAR' },
        { value: 'RE', text: 'RÉUNION' },
        { value: 'RO', text: 'ROMANIA' },
        { value: 'RU', text: 'RUSSIAN FEDERATION' },
        { value: 'RW', text: 'RWANDA' },
        { value: 'SH', text: 'SAINT HELENA' },
        { value: 'KN', text: 'SAINT KITTS AND NEVIS' },
        { value: 'LC', text: 'SAINT LUCIA' },
        { value: 'PM', text: 'SAINT PIERRE AND MIQUELON' },
        { value: 'VC', text: 'SAINT VINCENT AND THE GRENADINES' },
        { value: 'WS', text: 'SAMOA' },
        { value: 'SM', text: 'SAN MARINO' },
        { value: 'ST', text: 'SAO TOME AND PRINCIPE' },
        { value: 'SA', text: 'SAUDI ARABIA' },
        { value: 'SN', text: 'SENEGAL' },
        { value: 'CS', text: 'SERBIA AND MONTENEGRO' },
        { value: 'SC', text: 'SEYCHELLES' },
        { value: 'SL', text: 'SIERRA LEONE' },
        { value: 'SG', text: 'SINGAPORE' },
        { value: 'SK', text: 'SLOVAKIA' },
        { value: 'SI', text: 'SLOVENIA' },
        { value: 'SB', text: 'SOLOMON ISLANDS' },
        { value: 'SO', text: 'SOMALIA' },
        { value: 'ZA', text: 'SOUTH AFRICA' },
        { value: 'GS', text: 'SOUTH GEORGIA AND SOUTH SANDWICH ISLANDS' },
        { value: 'ES', text: 'SPAIN' },
        { value: 'LK', text: 'SRI LANKA' },
        { value: 'SD', text: 'SUDAN' },
        { value: 'SR', text: 'SURINAME' },
        { value: 'SJ', text: 'SVALBARD AND JAN MAYEN' },
        { value: 'SZ', text: 'SWAZILAND' },
        { value: 'SE', text: 'SWEDEN' },
        { value: 'CH', text: 'SWITZERLAND' },
        { value: 'SY', text: 'SYRIAN ARAB REPUBLIC' },
        { value: 'TW', text: 'TAIWAN, PROVINCE OF CHINA' },
        { value: 'TJ', text: 'TAJIKISTAN' },
        { value: 'TZ', text: 'TANZANIA, UNITED REPUBLIC OF' },
        { value: 'TH', text: 'THAILAND' },
        { value: 'TL', text: 'TIMOR-LESTE' },
        { value: 'TG', text: 'TOGO' },
        { value: 'TK', text: 'TOKELAU' },
        { value: 'TO', text: 'TONGA' },
        { value: 'TT', text: 'TRINIDAD AND TOBAGO' },
        { value: 'TN', text: 'TUNISIA' },
        { value: 'TR', text: 'TURKEY' },
        { value: 'TM', text: 'TURKMENISTAN' },
        { value: 'TC', text: 'TURKS AND CAICOS ISLANDS' },
        { value: 'TV', text: 'TUVALU' },
        { value: 'UG', text: 'UGANDA' },
        { value: 'UA', text: 'UKRAINE' },
        { value: 'AE', text: 'UNITED ARAB EMIRATES' },
        { value: 'GB', text: 'UNITED KINGDOM' },
        { value: 'US', text: 'UNITED STATES' },
        { value: 'UM', text: 'UNITED STATES MINOR OUTLYING ISLANDS' },
        { value: 'UY', text: 'URUGUAY' },
        { value: 'UZ', text: 'UZBEKISTAN' },
        { value: 'VU', text: 'VANUATU' },
        { value: 'VN', text: 'VIET NAM' },
        { value: 'VG', text: 'VIRGIN ISLANDS, BRITISH' },
        { value: 'VI', text: 'VIRGIN ISLANDS, U.S.' },
        { value: 'WF', text: 'WALLIS AND FUTUNA' },
        { value: 'EH', text: 'WESTERN SAHARA' },
        { value: 'YE', text: 'YEMEN' },
        { value: 'ZW', text: 'ZIMBABWE' }
    ],

    constructor: function() {
        this.initConfig({
            operatorsMap: Ext.Array.toValueMap(this.operators, 'id'),
            prefixesMap: Ext.Array.toValueMap(this.prefixes, 'value'),
            protocolsMap: Ext.Array.toValueMap(this.protocols, 'value'),
            countriesMap: Ext.Array.toValueMap(this.countries, 'value')
            // columns: columns
        });
    }


});
