Ext.define('Mfw.Globals', {
    alternateClassName: 'Globals',
    singleton: true,

    timezones: [
        { text: 'UTC',                            value: 'UTC' }, // default value
        { text: 'Africa/Abidjan',                 value: 'GMT0' },
        { text: 'Africa/Accra',                   value: 'GMT0' },
        { text: 'Africa/Addis Ababa',             value: 'EAT-3' },
        { text: 'Africa/Algiers',                 value: 'CET-1' },
        { text: 'Africa/Asmara',                  value: 'EAT-3' },
        { text: 'Africa/Bamako',                  value: 'GMT0' },
        { text: 'Africa/Bangui',                  value: 'WAT-1' },
        { text: 'Africa/Banjul',                  value: 'GMT0' },
        { text: 'Africa/Bissau',                  value: 'GMT0' },
        { text: 'Africa/Blantyre',                value: 'CAT-2' },
        { text: 'Africa/Brazzaville',             value: 'WAT-1' },
        { text: 'Africa/Bujumbura',               value: 'CAT-2' },
        { text: 'Africa/Casablanca',              value: 'WET0' },
        { text: 'Africa/Ceuta',                   value: 'CET-1CEST,M3.5.0,M10.5.0/3' },
        { text: 'Africa/Conakry',                 value: 'GMT0' },
        { text: 'Africa/Dakar',                   value: 'GMT0' },
        { text: 'Africa/Dar es Salaam',           value: 'EAT-3' },
        { text: 'Africa/Djibouti',                value: 'EAT-3' },
        { text: 'Africa/Douala',                  value: 'WAT-1' },
        { text: 'Africa/El Aaiun',                value: 'WET0' },
        { text: 'Africa/Freetown',                value: 'GMT0' },
        { text: 'Africa/Gaborone',                value: 'CAT-2' },
        { text: 'Africa/Harare',                  value: 'CAT-2' },
        { text: 'Africa/Johannesburg',            value: 'SAST-2' },
        { text: 'Africa/Kampala',                 value: 'EAT-3' },
        { text: 'Africa/Khartoum',                value: 'EAT-3' },
        { text: 'Africa/Kigali',                  value: 'CAT-2' },
        { text: 'Africa/Kinshasa',                value: 'WAT-1' },
        { text: 'Africa/Lagos',                   value: 'WAT-1' },
        { text: 'Africa/Libreville',              value: 'WAT-1' },
        { text: 'Africa/Lome',                    value: 'GMT0' },
        { text: 'Africa/Luanda',                  value: 'WAT-1' },
        { text: 'Africa/Lubumbashi',              value: 'CAT-2' },
        { text: 'Africa/Lusaka',                  value: 'CAT-2' },
        { text: 'Africa/Malabo',                  value: 'WAT-1' },
        { text: 'Africa/Maputo',                  value: 'CAT-2' },
        { text: 'Africa/Maseru',                  value: 'SAST-2' },
        { text: 'Africa/Mbabane',                 value: 'SAST-2' },
        { text: 'Africa/Mogadishu',               value: 'EAT-3' },
        { text: 'Africa/Monrovia',                value: 'GMT0' },
        { text: 'Africa/Nairobi',                 value: 'EAT-3' },
        { text: 'Africa/Ndjamena',                value: 'WAT-1' },
        { text: 'Africa/Niamey',                  value: 'WAT-1' },
        { text: 'Africa/Nouakchott',              value: 'GMT0' },
        { text: 'Africa/Ouagadougou',             value: 'GMT0' },
        { text: 'Africa/Porto-Novo',              value: 'WAT-1' },
        { text: 'Africa/Sao Tome',                value: 'GMT0' },
        { text: 'Africa/Tripoli',                 value: 'EET-2' },
        { text: 'Africa/Tunis',                   value: 'CET-1' },
        { text: 'Africa/Windhoek',                value: 'WAT-1WAST,M9.1.0,M4.1.0' },
        { text: 'America/Adak',                   value: 'HAST10HADT,M3.2.0,M11.1.0' },
        { text: 'America/Anchorage',              value: 'AKST9AKDT,M3.2.0,M11.1.0' },
        { text: 'America/Anguilla',               value: 'AST4' },
        { text: 'America/Antigua',                value: 'AST4' },
        { text: 'America/Araguaina',              value: 'BRT3' },
        { text: 'America/Argentina/Buenos Aires', value: 'ART3' },
        { text: 'America/Argentina/Catamarca',    value: 'ART3' },
        { text: 'America/Argentina/Cordoba',      value: 'ART3' },
        { text: 'America/Argentina/Jujuy',        value: 'ART3' },
        { text: 'America/Argentina/La Rioja',     value: 'ART3' },
        { text: 'America/Argentina/Mendoza',      value: 'ART3' },
        { text: 'America/Argentina/Rio Gallegos', value: 'ART3' },
        { text: 'America/Argentina/Salta',        value: 'ART3' },
        { text: 'America/Argentina/San Juan',     value: 'ART3' },
        { text: 'America/Argentina/Tucuman',      value: 'ART3' },
        { text: 'America/Argentina/Ushuaia',      value: 'ART3' },
        { text: 'America/Aruba',                  value: 'AST4' },
        { text: 'America/Asuncion',               value: 'PYT4PYST,M10.1.0/0,M4.2.0/0' },
        { text: 'America/Atikokan',               value: 'EST5' },
        { text: 'America/Bahia',                  value: 'BRT3' },
        { text: 'America/Barbados',               value: 'AST4' },
        { text: 'America/Belem',                  value: 'BRT3' },
        { text: 'America/Belize',                 value: 'CST6' },
        { text: 'America/Blanc-Sablon',           value: 'AST4' },
        { text: 'America/Boa Vista',              value: 'AMT4' },
        { text: 'America/Bogota',                 value: 'COT5' },
        { text: 'America/Boise',                  value: 'MST7MDT,M3.2.0,M11.1.0' },
        { text: 'America/Cambridge Bay',          value: 'MST7MDT,M3.2.0,M11.1.0' },
        { text: 'America/Campo Grande',           value: 'AMT4AMST,M10.3.0/0,M2.3.0/0' },
        { text: 'America/Cancun',                 value: 'CST6CDT,M4.1.0,M10.5.0' },
        { text: 'America/Caracas',                value: 'VET4:30' },
        { text: 'America/Cayenne',                value: 'GFT3' },
        { text: 'America/Cayman',                 value: 'EST5' },
        { text: 'America/Chicago',                value: 'CST6CDT,M3.2.0,M11.1.0' },
        { text: 'America/Chihuahua',              value: 'MST7MDT,M4.1.0,M10.5.0' },
        { text: 'America/Costa Rica',             value: 'CST6' },
        { text: 'America/Cuiaba',                 value: 'AMT4AMST,M10.3.0/0,M2.3.0/0' },
        { text: 'America/Curacao',                value: 'AST4' },
        { text: 'America/Danmarkshavn',           value: 'GMT0' },
        { text: 'America/Dawson',                 value: 'PST8PDT,M3.2.0,M11.1.0' },
        { text: 'America/Dawson Creek',           value: 'MST7' },
        { text: 'America/Denver',                 value: 'MST7MDT,M3.2.0,M11.1.0' },
        { text: 'America/Detroit',                value: 'EST5EDT,M3.2.0,M11.1.0' },
        { text: 'America/Dominica',               value: 'AST4' },
        { text: 'America/Edmonton',               value: 'MST7MDT,M3.2.0,M11.1.0' },
        { text: 'America/Eirunepe',               value: 'AMT4' },
        { text: 'America/El Salvador',            value: 'CST6' },
        { text: 'America/Fortaleza',              value: 'BRT3' },
        { text: 'America/Glace Bay',              value: 'AST4ADT,M3.2.0,M11.1.0' },
        { text: 'America/Goose Bay',              value: 'AST4ADT,M3.2.0/0:01,M11.1.0/0:01' },
        { text: 'America/Grand Turk',             value: 'EST5EDT,M3.2.0,M11.1.0' },
        { text: 'America/Grenada',                value: 'AST4' },
        { text: 'America/Guadeloupe',             value: 'AST4' },
        { text: 'America/Guatemala',              value: 'CST6' },
        { text: 'America/Guayaquil',              value: 'ECT5' },
        { text: 'America/Guyana',                 value: 'GYT4' },
        { text: 'America/Halifax',                value: 'AST4ADT,M3.2.0,M11.1.0' },
        { text: 'America/Havana',                 value: 'CST5CDT,M3.2.0/0,M10.5.0/1' },
        { text: 'America/Hermosillo',             value: 'MST7' },
        { text: 'America/Indiana/Indianapolis',   value: 'EST5EDT,M3.2.0,M11.1.0' },
        { text: 'America/Indiana/Knox',           value: 'CST6CDT,M3.2.0,M11.1.0' },
        { text: 'America/Indiana/Marengo',        value: 'EST5EDT,M3.2.0,M11.1.0' },
        { text: 'America/Indiana/Petersburg',     value: 'EST5EDT,M3.2.0,M11.1.0' },
        { text: 'America/Indiana/Tell City',      value: 'CST6CDT,M3.2.0,M11.1.0' },
        { text: 'America/Indiana/Vevay',          value: 'EST5EDT,M3.2.0,M11.1.0' },
        { text: 'America/Indiana/Vincennes',      value: 'EST5EDT,M3.2.0,M11.1.0' },
        { text: 'America/Indiana/Winamac',        value: 'EST5EDT,M3.2.0,M11.1.0' },
        { text: 'America/Inuvik',                 value: 'MST7MDT,M3.2.0,M11.1.0' },
        { text: 'America/Iqaluit',                value: 'EST5EDT,M3.2.0,M11.1.0' },
        { text: 'America/Jamaica',                value: 'EST5' },
        { text: 'America/Juneau',                 value: 'AKST9AKDT,M3.2.0,M11.1.0' },
        { text: 'America/Kentucky/Louisville',    value: 'EST5EDT,M3.2.0,M11.1.0' },
        { text: 'America/Kentucky/Monticello',    value: 'EST5EDT,M3.2.0,M11.1.0' },
        { text: 'America/La Paz',                 value: 'BOT4' },
        { text: 'America/Lima',                   value: 'PET5' },
        { text: 'America/Los Angeles',            value: 'PST8PDT,M3.2.0,M11.1.0' },
        { text: 'America/Maceio',                 value: 'BRT3' },
        { text: 'America/Managua',                value: 'CST6' },
        { text: 'America/Manaus',                 value: 'AMT4' },
        { text: 'America/Marigot',                value: 'AST4' },
        { text: 'America/Martinique',             value: 'AST4' },
        { text: 'America/Matamoros',              value: 'CST6CDT,M3.2.0,M11.1.0' },
        { text: 'America/Mazatlan',               value: 'MST7MDT,M4.1.0,M10.5.0' },
        { text: 'America/Menominee',              value: 'CST6CDT,M3.2.0,M11.1.0' },
        { text: 'America/Merida',                 value: 'CST6CDT,M4.1.0,M10.5.0' },
        { text: 'America/Mexico City',            value: 'CST6CDT,M4.1.0,M10.5.0' },
        { text: 'America/Miquelon',               value: 'PMST3PMDT,M3.2.0,M11.1.0' },
        { text: 'America/Moncton',                value: 'AST4ADT,M3.2.0,M11.1.0' },
        { text: 'America/Monterrey',              value: 'CST6CDT,M4.1.0,M10.5.0' },
        { text: 'America/Montevideo',             value: 'UYT3UYST,M10.1.0,M3.2.0' },
        { text: 'America/Montreal',               value: 'EST5EDT,M3.2.0,M11.1.0' },
        { text: 'America/Montserrat',             value: 'AST4' },
        { text: 'America/Nassau',                 value: 'EST5EDT,M3.2.0,M11.1.0' },
        { text: 'America/New York',               value: 'EST5EDT,M3.2.0,M11.1.0' },
        { text: 'America/Nipigon',                value: 'EST5EDT,M3.2.0,M11.1.0' },
        { text: 'America/Nome',                   value: 'AKST9AKDT,M3.2.0,M11.1.0' },
        { text: 'America/Noronha',                value: 'FNT2' },
        { text: 'America/North Dakota/Center',    value: 'CST6CDT,M3.2.0,M11.1.0' },
        { text: 'America/North Dakota/New Salem', value: 'CST6CDT,M3.2.0,M11.1.0' },
        { text: 'America/Ojinaga',                value: 'MST7MDT,M3.2.0,M11.1.0' },
        { text: 'America/Panama',                 value: 'EST5' },
        { text: 'America/Pangnirtung',            value: 'EST5EDT,M3.2.0,M11.1.0' },
        { text: 'America/Paramaribo',             value: 'SRT3' },
        { text: 'America/Phoenix',                value: 'MST7' },
        { text: 'America/Port of Spain',          value: 'AST4' },
        { text: 'America/Port-au-Prince',         value: 'EST5' },
        { text: 'America/Porto Velho',            value: 'AMT4' },
        { text: 'America/Puerto Rico',            value: 'AST4' },
        { text: 'America/Rainy River',            value: 'CST6CDT,M3.2.0,M11.1.0' },
        { text: 'America/Rankin Inlet',           value: 'CST6CDT,M3.2.0,M11.1.0' },
        { text: 'America/Recife',                 value: 'BRT3' },
        { text: 'America/Regina',                 value: 'CST6' },
        { text: 'America/Rio Branco',             value: 'AMT4' },
        { text: 'America/Santa Isabel',           value: 'PST8PDT,M4.1.0,M10.5.0' },
        { text: 'America/Santarem',               value: 'BRT3' },
        { text: 'America/Santo Domingo',          value: 'AST4' },
        { text: 'America/Sao Paulo',              value: 'BRT3BRST,M10.3.0/0,M2.3.0/0' },
        { text: 'America/Scoresbysund',           value: 'EGT1EGST,M3.5.0/0,M10.5.0/1' },
        { text: 'America/Shiprock',               value: 'MST7MDT,M3.2.0,M11.1.0' },
        { text: 'America/St Barthelemy',          value: 'AST4' },
        { text: 'America/St Johns',               value: 'NST3:30NDT,M3.2.0/0:01,M11.1.0/0:01' },
        { text: 'America/St Kitts',               value: 'AST4' },
        { text: 'America/St Lucia',               value: 'AST4' },
        { text: 'America/St Thomas',              value: 'AST4' },
        { text: 'America/St Vincent',             value: 'AST4' },
        { text: 'America/Swift Current',          value: 'CST6' },
        { text: 'America/Tegucigalpa',            value: 'CST6' },
        { text: 'America/Thule',                  value: 'AST4ADT,M3.2.0,M11.1.0' },
        { text: 'America/Thunder Bay',            value: 'EST5EDT,M3.2.0,M11.1.0' },
        { text: 'America/Tijuana',                value: 'PST8PDT,M3.2.0,M11.1.0' },
        { text: 'America/Toronto',                value: 'EST5EDT,M3.2.0,M11.1.0' },
        { text: 'America/Tortola',                value: 'AST4' },
        { text: 'America/Vancouver',              value: 'PST8PDT,M3.2.0,M11.1.0' },
        { text: 'America/Whitehorse',             value: 'PST8PDT,M3.2.0,M11.1.0' },
        { text: 'America/Winnipeg',               value: 'CST6CDT,M3.2.0,M11.1.0' },
        { text: 'America/Yakutat',                value: 'AKST9AKDT,M3.2.0,M11.1.0' },
        { text: 'America/Yellowknife',            value: 'MST7MDT,M3.2.0,M11.1.0' },
        { text: 'Antarctica/Casey',               value: 'WST-8' },
        { text: 'Antarctica/Davis',               value: 'DAVT-7' },
        { text: 'Antarctica/DumontDUrville',      value: 'DDUT-10' },
        { text: 'Antarctica/Macquarie',           value: 'MIST-11' },
        { text: 'Antarctica/Mawson',              value: 'MAWT-5' },
        { text: 'Antarctica/McMurdo',             value: 'NZST-12NZDT,M9.5.0,M4.1.0/3' },
        { text: 'Antarctica/Rothera',             value: 'ROTT3' },
        { text: 'Antarctica/South Pole',          value: 'NZST-12NZDT,M9.5.0,M4.1.0/3' },
        { text: 'Antarctica/Syowa',               value: 'SYOT-3' },
        { text: 'Antarctica/Vostok',              value: 'VOST-6' },
        { text: 'Arctic/Longyearbyen',            value: 'CET-1CEST,M3.5.0,M10.5.0/3' },
        { text: 'Asia/Aden',                      value: 'AST-3' },
        { text: 'Asia/Almaty',                    value: 'ALMT-6' },
        { text: 'Asia/Anadyr',                    value: 'ANAT-11ANAST,M3.5.0,M10.5.0/3' },
        { text: 'Asia/Aqtau',                     value: 'AQTT-5' },
        { text: 'Asia/Aqtobe',                    value: 'AQTT-5' },
        { text: 'Asia/Ashgabat',                  value: 'TMT-5' },
        { text: 'Asia/Baghdad',                   value: 'AST-3' },
        { text: 'Asia/Bahrain',                   value: 'AST-3' },
        { text: 'Asia/Baku',                      value: 'AZT-4AZST,M3.5.0/4,M10.5.0/5' },
        { text: 'Asia/Bangkok',                   value: 'ICT-7' },
        { text: 'Asia/Beirut',                    value: 'EET-2EEST,M3.5.0/0,M10.5.0/0' },
        { text: 'Asia/Bishkek',                   value: 'KGT-6' },
        { text: 'Asia/Brunei',                    value: 'BNT-8' },
        { text: 'Asia/Choibalsan',                value: 'CHOT-8' },
        { text: 'Asia/Chongqing',                 value: 'CST-8' },
        { text: 'Asia/Colombo',                   value: 'IST-5:30' },
        { text: 'Asia/Damascus',                  value: 'EET-2EEST,M4.1.5/0,M10.5.5/0' },
        { text: 'Asia/Dhaka',                     value: 'BDT-6' },
        { text: 'Asia/Dili',                      value: 'TLT-9' },
        { text: 'Asia/Dubai',                     value: 'GST-4' },
        { text: 'Asia/Dushanbe',                  value: 'TJT-5' },
        { text: 'Asia/Gaza',                      value: 'EET-2EEST,M3.5.6/0:01,M9.1.5' },
        { text: 'Asia/Harbin',                    value: 'CST-8' },
        { text: 'Asia/Ho Chi Minh',               value: 'ICT-7' },
        { text: 'Asia/Hong Kong',                 value: 'HKT-8' },
        { text: 'Asia/Hovd',                      value: 'HOVT-7' },
        { text: 'Asia/Irkutsk',                   value: 'IRKT-8IRKST,M3.5.0,M10.5.0/3' },
        { text: 'Asia/Jakarta',                   value: 'WIT-7' },
        { text: 'Asia/Jayapura',                  value: 'EIT-9' },
        { text: 'Asia/Kabul',                     value: 'AFT-4:30' },
        { text: 'Asia/Kamchatka',                 value: 'PETT-11PETST,M3.5.0,M10.5.0/3' },
        { text: 'Asia/Karachi',                   value: 'PKT-5' },
        { text: 'Asia/Kashgar',                   value: 'CST-8' },
        { text: 'Asia/Kathmandu',                 value: 'NPT-5:45' },
        { text: 'Asia/Kolkata',                   value: 'IST-5:30' },
        { text: 'Asia/Krasnoyarsk',               value: 'KRAT-7KRAST,M3.5.0,M10.5.0/3' },
        { text: 'Asia/Kuala Lumpur',              value: 'MYT-8' },
        { text: 'Asia/Kuching',                   value: 'MYT-8' },
        { text: 'Asia/Kuwait',                    value: 'AST-3' },
        { text: 'Asia/Macau',                     value: 'CST-8' },
        { text: 'Asia/Magadan',                   value: 'MAGT-11MAGST,M3.5.0,M10.5.0/3' },
        { text: 'Asia/Makassar',                  value: 'CIT-8' },
        { text: 'Asia/Manila',                    value: 'PHT-8' },
        { text: 'Asia/Muscat',                    value: 'GST-4' },
        { text: 'Asia/Nicosia',                   value: 'EET-2EEST,M3.5.0/3,M10.5.0/4' },
        { text: 'Asia/Novokuznetsk',              value: 'NOVT-6NOVST,M3.5.0,M10.5.0/3' },
        { text: 'Asia/Novosibirsk',               value: 'NOVT-6NOVST,M3.5.0,M10.5.0/3' },
        { text: 'Asia/Omsk',                      value: 'OMST-7' },
        { text: 'Asia/Oral',                      value: 'ORAT-5' },
        { text: 'Asia/Phnom Penh',                value: 'ICT-7' },
        { text: 'Asia/Pontianak',                 value: 'WIT-7' },
        { text: 'Asia/Pyongyang',                 value: 'KST-9' },
        { text: 'Asia/Qatar',                     value: 'AST-3' },
        { text: 'Asia/Qyzylorda',                 value: 'QYZT-6' },
        { text: 'Asia/Rangoon',                   value: 'MMT-6:30' },
        { text: 'Asia/Riyadh',                    value: 'AST-3' },
        { text: 'Asia/Sakhalin',                  value: 'SAKT-10SAKST,M3.5.0,M10.5.0/3' },
        { text: 'Asia/Samarkand',                 value: 'UZT-5' },
        { text: 'Asia/Seoul',                     value: 'KST-9' },
        { text: 'Asia/Shanghai',                  value: 'CST-8' },
        { text: 'Asia/Singapore',                 value: 'SGT-8' },
        { text: 'Asia/Taipei',                    value: 'CST-8' },
        { text: 'Asia/Tashkent',                  value: 'UZT-5' },
        { text: 'Asia/Tbilisi',                   value: 'GET-4' },
        { text: 'Asia/Tehran',                    value: 'IRST-3:30IRDT,80/0,264/0' },
        { text: 'Asia/Thimphu',                   value: 'BTT-6' },
        { text: 'Asia/Tokyo',                     value: 'JST-9' },
        { text: 'Asia/Ulaanbaatar',               value: 'ULAT-8' },
        { text: 'Asia/Urumqi',                    value: 'CST-8' },
        { text: 'Asia/Vientiane',                 value: 'ICT-7' },
        { text: 'Asia/Vladivostok',               value: 'VLAT-10VLAST,M3.5.0,M10.5.0/3' },
        { text: 'Asia/Yakutsk',                   value: 'YAKT-9YAKST,M3.5.0,M10.5.0/3' },
        { text: 'Asia/Yekaterinburg',             value: 'YEKT-5YEKST,M3.5.0,M10.5.0/3' },
        { text: 'Asia/Yerevan',                   value: 'AMT-4AMST,M3.5.0,M10.5.0/3' },
        { text: 'Atlantic/Azores',                value: 'AZOT1AZOST,M3.5.0/0,M10.5.0/1' },
        { text: 'Atlantic/Bermuda',               value: 'AST4ADT,M3.2.0,M11.1.0' },
        { text: 'Atlantic/Canary',                value: 'WET0WEST,M3.5.0/1,M10.5.0' },
        { text: 'Atlantic/Cape Verde',            value: 'CVT1' },
        { text: 'Atlantic/Faroe',                 value: 'WET0WEST,M3.5.0/1,M10.5.0' },
        { text: 'Atlantic/Madeira',               value: 'WET0WEST,M3.5.0/1,M10.5.0' },
        { text: 'Atlantic/Reykjavik',             value: 'GMT0' },
        { text: 'Atlantic/South Georgia',         value: 'GST2' },
        { text: 'Atlantic/St Helena',             value: 'GMT0' },
        { text: 'Atlantic/Stanley',               value: 'FKT4FKST,M9.1.0,M4.3.0' },
        { text: 'Australia/Adelaide',             value: 'CST-9:30CST,M10.1.0,M4.1.0/3' },
        { text: 'Australia/Brisbane',             value: 'EST-10' },
        { text: 'Australia/Broken Hill',          value: 'CST-9:30CST,M10.1.0,M4.1.0/3' },
        { text: 'Australia/Currie',               value: 'EST-10EST,M10.1.0,M4.1.0/3' },
        { text: 'Australia/Darwin',               value: 'CST-9:30' },
        { text: 'Australia/Eucla',                value: 'CWST-8:45' },
        { text: 'Australia/Hobart',               value: 'EST-10EST,M10.1.0,M4.1.0/3' },
        { text: 'Australia/Lindeman',             value: 'EST-10' },
        { text: 'Australia/Lord Howe',            value: 'LHST-10:30LHST-11,M10.1.0,M4.1.0' },
        { text: 'Australia/Melbourne',            value: 'EST-10EST,M10.1.0,M4.1.0/3' },
        { text: 'Australia/Perth',                value: 'WST-8' },
        { text: 'Australia/Sydney',               value: 'EST-10EST,M10.1.0,M4.1.0/3' },
        { text: 'Europe/Amsterdam',               value: 'CET-1CEST,M3.5.0,M10.5.0/3' },
        { text: 'Europe/Andorra',                 value: 'CET-1CEST,M3.5.0,M10.5.0/3' },
        { text: 'Europe/Athens',                  value: 'EET-2EEST,M3.5.0/3,M10.5.0/4' },
        { text: 'Europe/Belgrade',                value: 'CET-1CEST,M3.5.0,M10.5.0/3' },
        { text: 'Europe/Berlin',                  value: 'CET-1CEST,M3.5.0,M10.5.0/3' },
        { text: 'Europe/Bratislava',              value: 'CET-1CEST,M3.5.0,M10.5.0/3' },
        { text: 'Europe/Brussels',                value: 'CET-1CEST,M3.5.0,M10.5.0/3' },
        { text: 'Europe/Bucharest',               value: 'EET-2EEST,M3.5.0/3,M10.5.0/4' },
        { text: 'Europe/Budapest',                value: 'CET-1CEST,M3.5.0,M10.5.0/3' },
        { text: 'Europe/Chisinau',                value: 'EET-2EEST,M3.5.0/3,M10.5.0/4' },
        { text: 'Europe/Copenhagen',              value: 'CET-1CEST,M3.5.0,M10.5.0/3' },
        { text: 'Europe/Dublin',                  value: 'GMT0IST,M3.5.0/1,M10.5.0' },
        { text: 'Europe/Gibraltar',               value: 'CET-1CEST,M3.5.0,M10.5.0/3' },
        { text: 'Europe/Guernsey',                value: 'GMT0BST,M3.5.0/1,M10.5.0' },
        { text: 'Europe/Helsinki',                value: 'EET-2EEST,M3.5.0/3,M10.5.0/4' },
        { text: 'Europe/Isle of Man',             value: 'GMT0BST,M3.5.0/1,M10.5.0' },
        { text: 'Europe/Istanbul',                value: 'EET-2EEST,M3.5.0/3,M10.5.0/4' },
        { text: 'Europe/Jersey',                  value: 'GMT0BST,M3.5.0/1,M10.5.0' },
        { text: 'Europe/Kaliningrad',             value: 'EET-2EEST,M3.5.0,M10.5.0/3' },
        { text: 'Europe/Kiev',                    value: 'EET-2EEST,M3.5.0/3,M10.5.0/4' },
        { text: 'Europe/Lisbon',                  value: 'WET0WEST,M3.5.0/1,M10.5.0' },
        { text: 'Europe/Ljubljana',               value: 'CET-1CEST,M3.5.0,M10.5.0/3' },
        { text: 'Europe/London',                  value: 'GMT0BST,M3.5.0/1,M10.5.0' },
        { text: 'Europe/Luxembourg',              value: 'CET-1CEST,M3.5.0,M10.5.0/3' },
        { text: 'Europe/Madrid',                  value: 'CET-1CEST,M3.5.0,M10.5.0/3' },
        { text: 'Europe/Malta',                   value: 'CET-1CEST,M3.5.0,M10.5.0/3' },
        { text: 'Europe/Mariehamn',               value: 'EET-2EEST,M3.5.0/3,M10.5.0/4' },
        { text: 'Europe/Minsk',                   value: 'EET-2EEST,M3.5.0,M10.5.0/3' },
        { text: 'Europe/Monaco',                  value: 'CET-1CEST,M3.5.0,M10.5.0/3' },
        { text: 'Europe/Moscow',                  value: 'MSK-4' },
        { text: 'Europe/Oslo',                    value: 'CET-1CEST,M3.5.0,M10.5.0/3' },
        { text: 'Europe/Paris',                   value: 'CET-1CEST,M3.5.0,M10.5.0/3' },
        { text: 'Europe/Podgorica',               value: 'CET-1CEST,M3.5.0,M10.5.0/3' },
        { text: 'Europe/Prague',                  value: 'CET-1CEST,M3.5.0,M10.5.0/3' },
        { text: 'Europe/Riga',                    value: 'EET-2EEST,M3.5.0/3,M10.5.0/4' },
        { text: 'Europe/Rome',                    value: 'CET-1CEST,M3.5.0,M10.5.0/3' },
        { text: 'Europe/Samara',                  value: 'SAMT-3SAMST,M3.5.0,M10.5.0/3' },
        { text: 'Europe/San Marino',              value: 'CET-1CEST,M3.5.0,M10.5.0/3' },
        { text: 'Europe/Sarajevo',                value: 'CET-1CEST,M3.5.0,M10.5.0/3' },
        { text: 'Europe/Simferopol',              value: 'EET-2EEST,M3.5.0/3,M10.5.0/4' },
        { text: 'Europe/Skopje',                  value: 'CET-1CEST,M3.5.0,M10.5.0/3' },
        { text: 'Europe/Sofia',                   value: 'EET-2EEST,M3.5.0/3,M10.5.0/4' },
        { text: 'Europe/Stockholm',               value: 'CET-1CEST,M3.5.0,M10.5.0/3' },
        { text: 'Europe/Tallinn',                 value: 'EET-2EEST,M3.5.0/3,M10.5.0/4' },
        { text: 'Europe/Tirane',                  value: 'CET-1CEST,M3.5.0,M10.5.0/3' },
        { text: 'Europe/Uzhgorod',                value: 'EET-2EEST,M3.5.0/3,M10.5.0/4' },
        { text: 'Europe/Vaduz',                   value: 'CET-1CEST,M3.5.0,M10.5.0/3' },
        { text: 'Europe/Vatican',                 value: 'CET-1CEST,M3.5.0,M10.5.0/3' },
        { text: 'Europe/Vienna',                  value: 'CET-1CEST,M3.5.0,M10.5.0/3' },
        { text: 'Europe/Vilnius',                 value: 'EET-2EEST,M3.5.0/3,M10.5.0/4' },
        { text: 'Europe/Volgograd',               value: 'VOLT-3VOLST,M3.5.0,M10.5.0/3' },
        { text: 'Europe/Warsaw',                  value: 'CET-1CEST,M3.5.0,M10.5.0/3' },
        { text: 'Europe/Zagreb',                  value: 'CET-1CEST,M3.5.0,M10.5.0/3' },
        { text: 'Europe/Zaporozhye',              value: 'EET-2EEST,M3.5.0/3,M10.5.0/4' },
        { text: 'Europe/Zurich',                  value: 'CET-1CEST,M3.5.0,M10.5.0/3' },
        { text: 'Indian/Antananarivo',            value: 'EAT-3' },
        { text: 'Indian/Chagos',                  value: 'IOT-6' },
        { text: 'Indian/Christmas',               value: 'CXT-7' },
        { text: 'Indian/Cocos',                   value: 'CCT-6:30' },
        { text: 'Indian/Comoro',                  value: 'EAT-3' },
        { text: 'Indian/Kerguelen',               value: 'TFT-5' },
        { text: 'Indian/Mahe',                    value: 'SCT-4' },
        { text: 'Indian/Maldives',                value: 'MVT-5' },
        { text: 'Indian/Mauritius',               value: 'MUT-4' },
        { text: 'Indian/Mayotte',                 value: 'EAT-3' },
        { text: 'Indian/Reunion',                 value: 'RET-4' },
        { text: 'Pacific/Apia',                   value: 'WST11' },
        { text: 'Pacific/Auckland',               value: 'NZST-12NZDT,M9.5.0,M4.1.0/3' },
        { text: 'Pacific/Chatham',                value: 'CHAST-12:45CHADT,M9.5.0/2:45,M4.1.0/3:45' },
        { text: 'Pacific/Efate',                  value: 'VUT-11' },
        { text: 'Pacific/Enderbury',              value: 'PHOT-13' },
        { text: 'Pacific/Fakaofo',                value: 'TKT10' },
        { text: 'Pacific/Fiji',                   value: 'FJT-12' },
        { text: 'Pacific/Funafuti',               value: 'TVT-12' },
        { text: 'Pacific/Galapagos',              value: 'GALT6' },
        { text: 'Pacific/Gambier',                value: 'GAMT9' },
        { text: 'Pacific/Guadalcanal',            value: 'SBT-11' },
        { text: 'Pacific/Guam',                   value: 'ChST-10' },
        { text: 'Pacific/Honolulu',               value: 'HST10' },
        { text: 'Pacific/Johnston',               value: 'HST10' },
        { text: 'Pacific/Kiritimati',             value: 'LINT-14' },
        { text: 'Pacific/Kosrae',                 value: 'KOST-11' },
        { text: 'Pacific/Kwajalein',              value: 'MHT-12' },
        { text: 'Pacific/Majuro',                 value: 'MHT-12' },
        { text: 'Pacific/Marquesas',              value: 'MART9:30' },
        { text: 'Pacific/Midway',                 value: 'SST11' },
        { text: 'Pacific/Nauru',                  value: 'NRT-12' },
        { text: 'Pacific/Niue',                   value: 'NUT11' },
        { text: 'Pacific/Norfolk',                value: 'NFT-11:30' },
        { text: 'Pacific/Noumea',                 value: 'NCT-11' },
        { text: 'Pacific/Pago Pago',              value: 'SST11' },
        { text: 'Pacific/Palau',                  value: 'PWT-9' },
        { text: 'Pacific/Pitcairn',               value: 'PST8' },
        { text: 'Pacific/Ponape',                 value: 'PONT-11' },
        { text: 'Pacific/Port Moresby',           value: 'PGT-10' },
        { text: 'Pacific/Rarotonga',              value: 'CKT10' },
        { text: 'Pacific/Saipan',                 value: 'ChST-10' },
        { text: 'Pacific/Tahiti',                 value: 'TAHT10' },
        { text: 'Pacific/Tarawa',                 value: 'GILT-12' },
        { text: 'Pacific/Tongatapu',              value: 'TOT-13' },
        { text: 'Pacific/Truk',                   value: 'TRUT-10' },
        { text: 'Pacific/Wake',                   value: 'WAKT-12' },
        { text: 'Pacific/Wallis',                 value: 'WFT-12'}
    ],

    protocols: [
        { text: 'HOPOPT', value: 0 },
        { text: 'ICMP', value: 1 },
        { text: 'IGMP', value: 2 },
        { text: 'GGP', value: 3 },
        { text: 'IP-in-IP', value: 4 },
        { text: 'ST', value: 5 },
        { text: 'TCP', value: 6 },
        { text: 'CBT', value: 7 },
        { text: 'EGP', value: 8 },
        { text: 'IGP', value: 9 },
        { text: 'BBN-RCC-MON', value: 10 },
        { text: 'NVP-II', value: 11 },
        { text: 'PUP', value: 12 },
        { text: 'ARGUS', value: 13 },
        { text: 'EMCON', value: 14 },
        { text: 'XNET', value: 15 },
        { text: 'CHAOS', value: 16 },
        { text: 'UDP', value: 17 },
        { text: 'MUX', value: 18 },
        { text: 'DCN-MEAS', value: 19 },
        { text: 'HMP', value: 20 },
        { text: 'PRM', value: 21 },
        { text: 'XNS-IDP', value: 22 },
        { text: 'TRUNK-1', value: 23 },
        { text: 'TRUNK-2', value: 24 },
        { text: 'LEAF-1', value: 25 },
        { text: 'LEAF-2', value: 26 },
        { text: 'RDP', value: 27 },
        { text: 'IRTP', value: 28 },
        { text: 'ISO-TP4', value: 29 },
        { text: 'NETBLT', value: 30 },
        { text: 'MFE-NSP', value: 31 },
        { text: 'MERIT-INP', value: 32 },
        { text: 'DCCP', value: 33 },
        { text: '3PC', value: 34 },
        { text: 'IDPR', value: 35 },
        { text: 'XTP', value: 36 },
        { text: 'DDP', value: 37 },
        { text: 'IDPR-CMTP', value: 38 },
        { text: 'TP++', value: 39 },
        { text: 'IL', value: 40 },
        { text: 'IPv6', value: 41 },
        { text: 'SDRP', value: 42 },
        { text: 'IPv6-Route', value: 43 },
        { text: 'IPv6-Frag', value: 44 },
        { text: 'IDRP', value: 45 },
        { text: 'RSVP', value: 46 },
        { text: 'GRE', value: 47 },
        { text: 'MHRP', value: 48 },
        { text: 'BNA', value: 49 },
        { text: 'ESP', value: 50 },
        { text: 'AH', value: 51 },
        { text: 'I-NLSP', value: 52 },
        { text: 'SWIPE', value: 53 },
        { text: 'NARP', value: 54 },
        { text: 'MOBILE', value: 55 },
        { text: 'TLSP', value: 56 },
        { text: 'SKIP', value: 57 },
        { text: 'IPv6-ICMP', value: 58 },
        { text: 'IPv6-NoNxt', value: 59 },
        { text: 'IPv6-Opts', value: 60 },
        { text: 'CFTP', value: 62 },
        { text: 'SAT-EXPAK', value: 64 },
        { text: 'KRYPTOLAN', value: 65 },
        { text: 'RVD', value: 66 },
        { text: 'IPPC', value: 67 },
        { text: 'SAT-MON', value: 69 },
        { text: 'VISA', value: 70 },
        { text: 'IPCU', value: 71 },
        { text: 'CPNX', value: 72 },
        { text: 'CPHB', value: 73 },
        { text: 'WSN', value: 74 },
        { text: 'PVP', value: 75 },
        { text: 'BR-SAT-MON', value: 76 },
        { text: 'SUN-ND', value: 77 },
        { text: 'WB-MON', value: 78 },
        { text: 'WB-EXPAK', value: 79 },
        { text: 'ISO-IP', value: 80 },
        { text: 'VMTP', value: 81 },
        { text: 'SECURE-VMTP', value: 82 },
        { text: 'VINES', value: 83 },
        { text: 'TTP', value: 84 },
        { text: 'NSFNET-IGP', value: 85 },
        { text: 'DGP', value: 86 },
        { text: 'TCF', value: 87 },
        { text: 'EIGRP', value: 88 },
        { text: 'OSPF', value: 89 },
        { text: 'Sprite-RPC', value: 90 },
        { text: 'LARP', value: 91 },
        { text: 'MTP', value: 92 },
        { text: 'AX.25', value: 93 },
        { text: 'IPIP', value: 94 },
        { text: 'MICP', value: 95 },
        { text: 'SCC-SP', value: 96 },
        { text: 'ETHERIP', value: 97 },
        { text: 'ENCAP', value: 98 },
        { text: 'GMTP', value: 100 },
        { text: 'IFMP', value: 101 },
        { text: 'PNNI', value: 102 },
        { text: 'PIM', value: 103 },
        { text: 'ARIS', value: 104 },
        { text: 'SCPS', value: 105 },
        { text: 'QNX', value: 106 },
        { text: 'A/N', value: 107 },
        { text: 'IPComp', value: 108 },
        { text: 'SNP', value: 109 },
        { text: 'Compaq-Peer', value: 110 },
        { text: 'IPX-in-IP', value: 111 },
        { text: 'VRRP', value: 112 },
        { text: 'PGM', value: 113 },
        { text: 'L2TP', value: 115 },
        { text: 'DDX', value: 116 },
        { text: 'IATP', value: 117 },
        { text: 'STP', value: 118 },
        { text: 'SRP', value: 119 },
        { text: 'UTI', value: 120 },
        { text: 'SMP', value: 121 },
        { text: 'SM', value: 122 },
        { text: 'PTP', value: 123 },
        { text: 'IS-IS', value: 124 },
        { text: 'FIRE', value: 125 },
        { text: 'CRTP', value: 126 },
        { text: 'CRUDP', value: 127 },
        { text: 'SSCOPMCE', value: 128 },
        { text: 'IPLT', value: 129 },
        { text: 'SPS', value: 130 },
        { text: 'PIPE', value: 131 },
        { text: 'SCTP', value: 132 },
        { text: 'FC', value: 133 },
        { text: 'RSVP-E2E-IGNORE', value: 134 },
        { text: 'Mobility', value: 135 },
        { text: 'UDPLite', value: 136 },
        { text: 'MPLS-in-IP', value: 137 },
        { text: 'manet', value: 138 },
        { text: 'HIP', value: 139 },
        { text: 'Shim6', value: 140 },
        { text: 'WESP', value: 141 },
        { text: 'ROHC', value: 142 }
    ],

    prefixes: [
        { value: '', text: 'Not set' },
        { value: 32, text: '/32 - 255.255.255.255' },
        { value: 31, text: '/31 - 255.255.255.254' },
        { value: 30, text: '/30 - 255.255.255.252' },
        { value: 29, text: '/29 - 255.255.255.248' },
        { value: 28, text: '/28 - 255.255.255.240' },
        { value: 27, text: '/27 - 255.255.255.224' },
        { value: 26, text: '/26 - 255.255.255.192' },
        { value: 25, text: '/25 - 255.255.255.128' },
        { value: 24, text: '/24 - 255.255.255.0' },
        { value: 23, text: '/23 - 255.255.254.0' },
        { value: 22, text: '/22 - 255.255.252.0' },
        { value: 21, text: '/21 - 255.255.248.0' },
        { value: 20, text: '/20 - 255.255.240.0' },
        { value: 19, text: '/19 - 255.255.224.0' },
        { value: 18, text: '/18 - 255.255.192.0' },
        { value: 17, text: '/17 - 255.255.128.0' },
        { value: 16, text: '/16 - 255.255.0.0' },
        { value: 15, text: '/15 - 255.254.0.0' },
        { value: 14, text: '/14 - 255.252.0.0' },
        { value: 13, text: '/13 - 255.248.0.0' },
        { value: 12, text: '/12 - 255.240.0.0' },
        { value: 11, text: '/11 - 255.224.0.0' },
        { value: 10, text: '/10 - 255.192.0.0' },
        { value: 9, text: '/9 - 255.128.0.0' },
        { value: 8, text: '/8 - 255.0.0.0' },
        { value: 7, text: '/7 - 254.0.0.0' },
        { value: 6, text: '/6 - 252.0.0.0' },
        { value: 5, text: '/5 - 248.0.0.0' },
        { value: 4, text: '/4 - 240.0.0.0' },
        { value: 3, text: '/3 - 224.0.0.0' },
        { value: 2, text: '/2 - 192.0.0.0' },
        { value: 1, text: '/1 - 128.0.0.0' },
        { value: 0, text: '/0 - 0.0.0.0' }
    ],

    operators: [
        { text: 'Equals'.t(),           value: 'EQ',       symbol: '='        },
        { text: 'Not Equals'.t(),       value: 'NE',       symbol: '!='       },
        { text: 'Greater Than'.t(),     value: 'GT',       symbol: '>'        },
        { text: 'Less Than'.t(),        value: 'LT',       symbol: '<'        },
        { text: 'Greater or Equal'.t(), value: 'GE',       symbol: '>='       },
        { text: 'Less or Equal'.t(),    value: 'LE',       symbol: '<='       },
        { text: 'Like'.t(),           value: 'LIKE',     symbol: 'like'     },
        { text: 'Not Like'.t(),   value: 'NOT_LIKE', symbol: 'not like' },
        { text: 'Is'.t(),               value: 'IS',       symbol: 'is'       },
        { text: 'Is Not'.t(),       value: 'IS_NOT',   symbol: 'is not'   },
        { text: 'In'.t(),               value: 'IN',       symbol: 'in'       },
        { text: 'Not In'.t(),       value: 'NOT_IN',   symbol: 'not in'   }
    ],

    countries: [
        { value: 'AF', text: 'AFGHANISTAN' },
        { value: 'AL', text: 'ALBANIA' },
        { value: 'DZ', text: 'ALGERIA' },
        { value: 'AS', text: 'AMERICAN SAMOA' },
        { value: 'AD', text: 'ANDORRA' },
        { value: 'AO', text: 'ANGOLA' },
        { value: 'AI', text: 'ANGUILLA' },
        { value: 'AQ', text: 'ANTARCTICA' },
        { value: 'AG', text: 'ANTIGUA AND BARBUDA' },
        { value: 'AR', text: 'ARGENTINA' },
        { value: 'AM', text: 'ARMENIA' },
        { value: 'AW', text: 'ARUBA' },
        { value: 'AU', text: 'AUSTRALIA' },
        { value: 'AT', text: 'AUSTRIA' },
        { value: 'AZ', text: 'AZERBAIJAN' },
        { value: 'BS', text: 'BAHAMAS' },
        { value: 'BH', text: 'BAHRAIN' },
        { value: 'BD', text: 'BANGLADESH' },
        { value: 'BB', text: 'BARBADOS' },
        { value: 'BY', text: 'BELARUS' },
        { value: 'BE', text: 'BELGIUM' },
        { value: 'BZ', text: 'BELIZE' },
        { value: 'BJ', text: 'BENIN' },
        { value: 'BM', text: 'BERMUDA' },
        { value: 'BT', text: 'BHUTAN' },
        { value: 'BO', text: 'OLIVIA' },
        { value: 'BA', text: 'BOSNIA AND HERZEGOVINA' },
        { value: 'BW', text: 'BOTSWANA' },
        { value: 'BV', text: 'BOUVET ISLAND' },
        { value: 'BR', text: 'BRAZIL' },
        { value: 'IO', text: 'BRITISH INDIAN OCEAN TERRITORY' },
        { value: 'BN', text: 'BRUNEI DARUSSALAM' },
        { value: 'BG', text: 'BULGARIA' },
        { value: 'BF', text: 'BURKINA FASO' },
        { value: 'BI', text: 'BURUNDI' },
        { value: 'KH', text: 'CAMBODIA' },
        { value: 'CM', text: 'CAMEROON' },
        { value: 'CA', text: 'CANADA' },
        { value: 'CV', text: 'CAPE VERDE' },
        { value: 'KY', text: 'CAYMAN ISLANDS' },
        { value: 'CF', text: 'CENTRAL AFRICAN REPUBLIC' },
        { value: 'TD', text: 'CHAD' },
        { value: 'CL', text: 'CHILE' },
        { value: 'CN', text: 'HINA' },
        { value: 'CX', text: 'HRISTMAS ISLAND' },
        { value: 'CC', text: 'COCOS (KEELING) ISLANDS' },
        { value: 'CO', text: 'COLOMBIA' },
        { value: 'KM', text: 'COMOROS' },
        { value: 'CG', text: 'CONGO' },
        { value: 'CD', text: 'CONGO, THE DEMOCRATIC REPUBLIC OF' },
        { value: 'CK', text: 'COOK ISLANDS' },
        { value: 'CR', text: 'COSTA RICA' },
        { value: 'CI', text: 'CÔTE D\'IVOIRE' },
        { value: 'HR', text: 'CROATIA' },
        { value: 'CU', text: 'CUBA' },
        { value: 'CY', text: 'CYPRUS' },
        { value: 'CZ', text: 'CZECH REPUBLIC' },
        { value: 'DK', text: 'DENMARK' },
        { value: 'DJ', text: 'DJIBOUTI' },
        { value: 'DM', text: 'DOMINICA' },
        { value: 'DO', text: 'DOMINICAN REPUBLIC' },
        { value: 'EC', text: 'ECUADOR' },
        { value: 'EG', text: 'EGYPT' },
        { value: 'SV', text: 'EL SALVADOR' },
        { value: 'GQ', text: 'EQUATORIAL GUINEA' },
        { value: 'ER', text: 'ERITREA' },
        { value: 'EE', text: 'ESTONIA' },
        { value: 'ET', text: 'ETHIOPIA' },
        { value: 'FK', text: 'FALKLAND ISLANDS (MALVINAS)' },
        { value: 'FO', text: 'AROE ISLANDS' },
        { value: 'FJ', text: 'FIJI' },
        { value: 'FI', text: 'FINLAND' },
        { value: 'FR', text: 'FRANCE' },
        { value: 'GF', text: 'FRENCH GUIANA' },
        { value: 'PF', text: 'FRENCH POLYNESIA' },
        { value: 'TF', text: 'FRENCH SOUTHERN TERRITORIES' },
        { value: 'GA', text: 'GABON' },
        { value: 'GM', text: 'GAMBIA' },
        { value: 'GE', text: 'GEORGIA' },
        { value: 'DE', text: 'GERMANY' },
        { value: 'GH', text: 'GHANA' },
        { value: 'GI', text: 'GIBRALTAR' },
        { value: 'GR', text: 'GREECE' },
        { value: 'GL', text: 'GREENLAND' },
        { value: 'GD', text: 'GRENADA' },
        { value: 'GP', text: 'GUADELOUPE' },
        { value: 'GU', text: 'GUAM' },
        { value: 'GT', text: 'GUATEMALA' },
        { value: 'GN', text: 'GUINEA' },
        { value: 'GW', text: 'GUINEA-BISSAU' },
        { value: 'GY', text: 'GUYANA' },
        { value: 'HT', text: 'HAITI' },
        { value: 'HM', text: 'HEARD ISLAND AND MCDONALD ISLANDS' },
        { value: 'HN', text: 'HONDURAS' },
        { value: 'HK', text: 'HONG KONG' },
        { value: 'HU', text: 'HUNGARY' },
        { value: 'IS', text: 'ICELAND' },
        { value: 'IN', text: 'INDIA' },
        { value: 'ID', text: 'INDONESIA' },
        { value: 'IR', text: 'IRAN, ISLAMIC REPUBLIC OF' },
        { value: 'IQ', text: 'IRAQ' },
        { value: 'IE', text: 'IRELAND' },
        { value: 'IL', text: 'ISRAEL' },
        { value: 'IT', text: 'ITALY' },
        { value: 'JM', text: 'JAMAICA' },
        { value: 'JP', text: 'JAPAN' },
        { value: 'JO', text: 'JORDAN' },
        { value: 'KZ', text: 'KAZAKHSTAN' },
        { value: 'KE', text: 'KENYA' },
        { value: 'KI', text: 'KIRIBATI' },
        { value: 'KP', text: 'KOREA, DEMOCRATIC PEOPLE\'S REPUBLIC OF' },
        { value: 'KR', text: 'KOREA, REPUBLIC OF' },
        { value: 'KW', text: 'KUWAIT' },
        { value: 'KG', text: 'KYRGYZSTAN' },
        { value: 'LA', text: 'LAO PEOPLE\'S DEMOCRATIC REPUBLIC' },
        { value: 'LV', text: 'LATVIA' },
        { value: 'LB', text: 'LEBANON' },
        { value: 'LS', text: 'LESOTHO' },
        { value: 'LR', text: 'LIBERIA' },
        { value: 'LY', text: 'LIBYAN ARAB JAMAHIRIYA' },
        { value: 'LI', text: 'LIECHTENSTEIN' },
        { value: 'LT', text: 'LITHUANIA' },
        { value: 'LU', text: 'LUXEMBOURG' },
        { value: 'MO', text: 'MACAO' },
        { value: 'MK', text: 'MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF' },
        { value: 'MG', text: 'MADAGASCAR' },
        { value: 'MW', text: 'MALAWI' },
        { value: 'MY', text: 'MALAYSIA' },
        { value: 'MV', text: 'MALDIVES' },
        { value: 'ML', text: 'MALI' },
        { value: 'MT', text: 'MALTA' },
        { value: 'MH', text: 'MARSHALL ISLANDS' },
        { value: 'MQ', text: 'MARTINIQUE' },
        { value: 'MR', text: 'MAURITANIA' },
        { value: 'MU', text: 'MAURITIUS' },
        { value: 'YT', text: 'MAYOTTE' },
        { value: 'MX', text: 'MEXICO' },
        { value: 'FM', text: 'MICRONESIA, FEDERATED STATES OF' },
        { value: 'MD', text: 'MOLDOVA, REPUBLIC OF' },
        { value: 'MC', text: 'MONACO' },
        { value: 'MN', text: 'MONGOLIA' },
        { value: 'MS', text: 'MONTSERRAT' },
        { value: 'MA', text: 'MOROCCO' },
        { value: 'MZ', text: 'MOZAMBIQUE' },
        { value: 'MM', text: 'MYANMAR' },
        { value: 'NA', text: 'NAMIBIA' },
        { value: 'NR', text: 'NAURU' },
        { value: 'NP', text: 'NEPAL' },
        { value: 'NL', text: 'NETHERLANDS' },
        { value: 'AN', text: 'NETHERLANDS ANTILLES' },
        { value: 'NC', text: 'NEW CALEDONIA' },
        { value: 'NZ', text: 'NEW ZEALAND' },
        { value: 'NI', text: 'NICARAGUA' },
        { value: 'NE', text: 'NIGER' },
        { value: 'NG', text: 'NIGERIA' },
        { value: 'NU', text: 'NIUE' },
        { value: 'NF', text: 'NORFOLK ISLAND' },
        { value: 'MP', text: 'NORTHERN MARIANA ISLANDS' },
        { value: 'NO', text: 'NORWAY' },
        { value: 'OM', text: 'OMAN' },
        { value: 'PK', text: 'PAKISTAN' },
        { value: 'PW', text: 'PALAU' },
        { value: 'PS', text: 'PALESTINIAN TERRITORY, OCCUPIED' },
        { value: 'PA', text: 'PANAMA' },
        { value: 'PG', text: 'PAPUA NEW GUINEA' },
        { value: 'PY', text: 'PARAGUAY' },
        { value: 'PE', text: 'PERU' },
        { value: 'PH', text: 'PHILIPPINES' },
        { value: 'PN', text: 'PITCAIRN' },
        { value: 'PL', text: 'POLAND' },
        { value: 'PT', text: 'PORTUGAL' },
        { value: 'PR', text: 'PUERTO RICO' },
        { value: 'QA', text: 'QATAR' },
        { value: 'RE', text: 'RÉUNION' },
        { value: 'RO', text: 'ROMANIA' },
        { value: 'RU', text: 'RUSSIAN FEDERATION' },
        { value: 'RW', text: 'RWANDA' },
        { value: 'SH', text: 'SAINT HELENA' },
        { value: 'KN', text: 'SAINT KITTS AND NEVIS' },
        { value: 'LC', text: 'SAINT LUCIA' },
        { value: 'PM', text: 'SAINT PIERRE AND MIQUELON' },
        { value: 'VC', text: 'SAINT VINCENT AND THE GRENADINES' },
        { value: 'WS', text: 'SAMOA' },
        { value: 'SM', text: 'SAN MARINO' },
        { value: 'ST', text: 'SAO TOME AND PRINCIPE' },
        { value: 'SA', text: 'SAUDI ARABIA' },
        { value: 'SN', text: 'SENEGAL' },
        { value: 'CS', text: 'SERBIA AND MONTENEGRO' },
        { value: 'SC', text: 'SEYCHELLES' },
        { value: 'SL', text: 'SIERRA LEONE' },
        { value: 'SG', text: 'SINGAPORE' },
        { value: 'SK', text: 'SLOVAKIA' },
        { value: 'SI', text: 'SLOVENIA' },
        { value: 'SB', text: 'SOLOMON ISLANDS' },
        { value: 'SO', text: 'SOMALIA' },
        { value: 'ZA', text: 'SOUTH AFRICA' },
        { value: 'GS', text: 'SOUTH GEORGIA AND SOUTH SANDWICH ISLANDS' },
        { value: 'ES', text: 'SPAIN' },
        { value: 'LK', text: 'SRI LANKA' },
        { value: 'SD', text: 'SUDAN' },
        { value: 'SR', text: 'SURINAME' },
        { value: 'SJ', text: 'SVALBARD AND JAN MAYEN' },
        { value: 'SZ', text: 'SWAZILAND' },
        { value: 'SE', text: 'SWEDEN' },
        { value: 'CH', text: 'SWITZERLAND' },
        { value: 'SY', text: 'SYRIAN ARAB REPUBLIC' },
        { value: 'TW', text: 'TAIWAN, PROVINCE OF CHINA' },
        { value: 'TJ', text: 'TAJIKISTAN' },
        { value: 'TZ', text: 'TANZANIA, UNITED REPUBLIC OF' },
        { value: 'TH', text: 'THAILAND' },
        { value: 'TL', text: 'TIMOR-LESTE' },
        { value: 'TG', text: 'TOGO' },
        { value: 'TK', text: 'TOKELAU' },
        { value: 'TO', text: 'TONGA' },
        { value: 'TT', text: 'TRINIDAD AND TOBAGO' },
        { value: 'TN', text: 'TUNISIA' },
        { value: 'TR', text: 'TURKEY' },
        { value: 'TM', text: 'TURKMENISTAN' },
        { value: 'TC', text: 'TURKS AND CAICOS ISLANDS' },
        { value: 'TV', text: 'TUVALU' },
        { value: 'UG', text: 'UGANDA' },
        { value: 'UA', text: 'UKRAINE' },
        { value: 'AE', text: 'UNITED ARAB EMIRATES' },
        { value: 'GB', text: 'UNITED KINGDOM' },
        { value: 'US', text: 'UNITED STATES' },
        { value: 'UM', text: 'UNITED STATES MINOR OUTLYING ISLANDS' },
        { value: 'UY', text: 'URUGUAY' },
        { value: 'UZ', text: 'UZBEKISTAN' },
        { value: 'VU', text: 'VANUATU' },
        { value: 'VN', text: 'VIET NAM' },
        { value: 'VG', text: 'VIRGIN ISLANDS, BRITISH' },
        { value: 'VI', text: 'VIRGIN ISLANDS, U.S.' },
        { value: 'WF', text: 'WALLIS AND FUTUNA' },
        { value: 'EH', text: 'WESTERN SAHARA' },
        { value: 'YE', text: 'YEMEN' },
        { value: 'ZW', text: 'ZIMBABWE' }
    ],

    constructor: function() {
        this.initConfig({
            operatorsMap: Ext.Array.toValueMap(this.operators, 'id'),
            prefixesMap: Ext.Array.toValueMap(this.prefixes, 'value'),
            protocolsMap: Ext.Array.toValueMap(this.protocols, 'value'),
            countriesMap: Ext.Array.toValueMap(this.countries, 'value')
            // columns: columns
        });
    }


});
