Ext.define('Mfw.Globals', {
    alternateClassName: 'Globals',
    singleton: true,

    protocols: [
        { text: 'HOPOPT', value: 0 },
        { text: 'ICMP', value: 1 },
        { text: 'IGMP', value: 2 },
        { text: 'GGP', value: 3 },
        { text: 'IP-in-IP', value: 4 },
        { text: 'ST', value: 5 },
        { text: 'TCP', value: 6 },
        { text: 'CBT', value: 7 },
        { text: 'EGP', value: 8 },
        { text: 'IGP', value: 9 },
        { text: 'BBN-RCC-MON', value: 10 },
        { text: 'NVP-II', value: 11 },
        { text: 'PUP', value: 12 },
        { text: 'ARGUS', value: 13 },
        { text: 'EMCON', value: 14 },
        { text: 'XNET', value: 15 },
        { text: 'CHAOS', value: 16 },
        { text: 'UDP', value: 17 },
        { text: 'MUX', value: 18 },
        { text: 'DCN-MEAS', value: 19 },
        { text: 'HMP', value: 20 },
        { text: 'PRM', value: 21 },
        { text: 'XNS-IDP', value: 22 },
        { text: 'TRUNK-1', value: 23 },
        { text: 'TRUNK-2', value: 24 },
        { text: 'LEAF-1', value: 25 },
        { text: 'LEAF-2', value: 26 },
        { text: 'RDP', value: 27 },
        { text: 'IRTP', value: 28 },
        { text: 'ISO-TP4', value: 29 },
        { text: 'NETBLT', value: 30 },
        { text: 'MFE-NSP', value: 31 },
        { text: 'MERIT-INP', value: 32 },
        { text: 'DCCP', value: 33 },
        { text: '3PC', value: 34 },
        { text: 'IDPR', value: 35 },
        { text: 'XTP', value: 36 },
        { text: 'DDP', value: 37 },
        { text: 'IDPR-CMTP', value: 38 },
        { text: 'TP++', value: 39 },
        { text: 'IL', value: 40 },
        { text: 'IPv6', value: 41 },
        { text: 'SDRP', value: 42 },
        { text: 'IPv6-Route', value: 43 },
        { text: 'IPv6-Frag', value: 44 },
        { text: 'IDRP', value: 45 },
        { text: 'RSVP', value: 46 },
        { text: 'GRE', value: 47 },
        { text: 'MHRP', value: 48 },
        { text: 'BNA', value: 49 },
        { text: 'ESP', value: 50 },
        { text: 'AH', value: 51 },
        { text: 'I-NLSP', value: 52 },
        { text: 'SWIPE', value: 53 },
        { text: 'NARP', value: 54 },
        { text: 'MOBILE', value: 55 },
        { text: 'TLSP', value: 56 },
        { text: 'SKIP', value: 57 },
        { text: 'IPv6-ICMP', value: 58 },
        { text: 'IPv6-NoNxt', value: 59 },
        { text: 'IPv6-Opts', value: 60 },
        { text: 'CFTP', value: 62 },
        { text: 'SAT-EXPAK', value: 64 },
        { text: 'KRYPTOLAN', value: 65 },
        { text: 'RVD', value: 66 },
        { text: 'IPPC', value: 67 },
        { text: 'SAT-MON', value: 69 },
        { text: 'VISA', value: 70 },
        { text: 'IPCU', value: 71 },
        { text: 'CPNX', value: 72 },
        { text: 'CPHB', value: 73 },
        { text: 'WSN', value: 74 },
        { text: 'PVP', value: 75 },
        { text: 'BR-SAT-MON', value: 76 },
        { text: 'SUN-ND', value: 77 },
        { text: 'WB-MON', value: 78 },
        { text: 'WB-EXPAK', value: 79 },
        { text: 'ISO-IP', value: 80 },
        { text: 'VMTP', value: 81 },
        { text: 'SECURE-VMTP', value: 82 },
        { text: 'VINES', value: 83 },
        { text: 'TTP', value: 84 },
        { text: 'NSFNET-IGP', value: 85 },
        { text: 'DGP', value: 86 },
        { text: 'TCF', value: 87 },
        { text: 'EIGRP', value: 88 },
        { text: 'OSPF', value: 89 },
        { text: 'Sprite-RPC', value: 90 },
        { text: 'LARP', value: 91 },
        { text: 'MTP', value: 92 },
        { text: 'AX.25', value: 93 },
        { text: 'IPIP', value: 94 },
        { text: 'MICP', value: 95 },
        { text: 'SCC-SP', value: 96 },
        { text: 'ETHERIP', value: 97 },
        { text: 'ENCAP', value: 98 },
        { text: 'GMTP', value: 100 },
        { text: 'IFMP', value: 101 },
        { text: 'PNNI', value: 102 },
        { text: 'PIM', value: 103 },
        { text: 'ARIS', value: 104 },
        { text: 'SCPS', value: 105 },
        { text: 'QNX', value: 106 },
        { text: 'A/N', value: 107 },
        { text: 'IPComp', value: 108 },
        { text: 'SNP', value: 109 },
        { text: 'Compaq-Peer', value: 110 },
        { text: 'IPX-in-IP', value: 111 },
        { text: 'VRRP', value: 112 },
        { text: 'PGM', value: 113 },
        { text: 'L2TP', value: 115 },
        { text: 'DDX', value: 116 },
        { text: 'IATP', value: 117 },
        { text: 'STP', value: 118 },
        { text: 'SRP', value: 119 },
        { text: 'UTI', value: 120 },
        { text: 'SMP', value: 121 },
        { text: 'SM', value: 122 },
        { text: 'PTP', value: 123 },
        { text: 'IS-IS', value: 124 },
        { text: 'FIRE', value: 125 },
        { text: 'CRTP', value: 126 },
        { text: 'CRUDP', value: 127 },
        { text: 'SSCOPMCE', value: 128 },
        { text: 'IPLT', value: 129 },
        { text: 'SPS', value: 130 },
        { text: 'PIPE', value: 131 },
        { text: 'SCTP', value: 132 },
        { text: 'FC', value: 133 },
        { text: 'RSVP-E2E-IGNORE', value: 134 },
        { text: 'Mobility', value: 135 },
        { text: 'UDPLite', value: 136 },
        { text: 'MPLS-in-IP', value: 137 },
        { text: 'manet', value: 138 },
        { text: 'HIP', value: 139 },
        { text: 'Shim6', value: 140 },
        { text: 'WESP', value: 141 },
        { text: 'ROHC', value: 142 }
    ],

    prefixes: [
        { value: 32, text: '/32 - 255.255.255.255' },
        { value: 31, text: '/31 - 255.255.255.254' },
        { value: 30, text: '/30 - 255.255.255.252' },
        { value: 29, text: '/29 - 255.255.255.248' },
        { value: 28, text: '/28 - 255.255.255.240' },
        { value: 27, text: '/27 - 255.255.255.224' },
        { value: 26, text: '/26 - 255.255.255.192' },
        { value: 25, text: '/25 - 255.255.255.128' },
        { value: 24, text: '/24 - 255.255.255.0' },
        { value: 23, text: '/23 - 255.255.254.0' },
        { value: 22, text: '/22 - 255.255.252.0' },
        { value: 21, text: '/21 - 255.255.248.0' },
        { value: 20, text: '/20 - 255.255.240.0' },
        { value: 19, text: '/19 - 255.255.224.0' },
        { value: 18, text: '/18 - 255.255.192.0' },
        { value: 17, text: '/17 - 255.255.128.0' },
        { value: 16, text: '/16 - 255.255.0.0' },
        { value: 15, text: '/15 - 255.254.0.0' },
        { value: 14, text: '/14 - 255.252.0.0' },
        { value: 13, text: '/13 - 255.248.0.0' },
        { value: 12, text: '/12 - 255.240.0.0' },
        { value: 11, text: '/11 - 255.224.0.0' },
        { value: 10, text: '/10 - 255.192.0.0' },
        { value: 9, text: '/9 - 255.128.0.0' },
        { value: 8, text: '/8 - 255.0.0.0' },
        { value: 7, text: '/7 - 254.0.0.0' },
        { value: 6, text: '/6 - 252.0.0.0' },
        { value: 5, text: '/5 - 248.0.0.0' },
        { value: 4, text: '/4 - 240.0.0.0' },
        { value: 3, text: '/3 - 224.0.0.0' },
        { value: 2, text: '/2 - 192.0.0.0' },
        { value: 1, text: '/1 - 128.0.0.0' },
        { value: 0, text: '/0 - 0.0.0.0' }
    ],

    operators: [
        { text: 'Equals'.t(),           value: 'EQ',       symbol: '='        },
        { text: 'Not Equals'.t(),       value: 'NE',       symbol: '!='       },
        { text: 'Greater Than'.t(),     value: 'GT',       symbol: '>'        },
        { text: 'Less Than'.t(),        value: 'LT',       symbol: '<'        },
        { text: 'Greater or Equal'.t(), value: 'GE',       symbol: '>='       },
        { text: 'Less or Equal'.t(),    value: 'LE',       symbol: '<='       },
        { text: 'Like'.t(),           value: 'LIKE',     symbol: 'like'     },
        { text: 'Not Like'.t(),   value: 'NOT_LIKE', symbol: 'not like' },
        { text: 'Is'.t(),               value: 'IS',       symbol: 'is'       },
        { text: 'Is Not'.t(),       value: 'IS_NOT',   symbol: 'is not'   },
        { text: 'In'.t(),               value: 'IN',       symbol: 'in'       },
        { text: 'Not In'.t(),       value: 'NOT_IN',   symbol: 'not in'   }
    ],

    constructor: function() {
        this.initConfig({
            operatorsMap: Ext.Array.toValueMap(this.operators, 'id'),
            prefixesMap: Ext.Array.toValueMap(this.prefixes, 'value'),
            protocolsMap: Ext.Array.toValueMap(this.protocols, 'value')
            // columns: columns
        });
    }


});
